// Theme preference and the page backgrounds. Kept free of imports so the
// boot guard can use it as the very first module in the bundle.

export type Theme = 'light' | 'dark' | 'auto'

export const THEME_KEY = 'colophon:theme'
export const SCHEME_LIGHT_KEY = 'colophon:scheme-light'
export const SCHEME_DARK_KEY = 'colophon:scheme-dark'

// One-time rename from the old prefix. This module loads first and stays
// import-free, so it migrates its own keys inline before the first read.
try {
  for (const [oldKey, newKey] of [
    ['mam-remaster:theme', THEME_KEY],
    ['mam-remaster:scheme-light', SCHEME_LIGHT_KEY],
    ['mam-remaster:scheme-dark', SCHEME_DARK_KEY],
  ]) {
    const value = localStorage.getItem(oldKey)
    if (value !== null) {
      if (localStorage.getItem(newKey) === null) localStorage.setItem(newKey, value)
      localStorage.removeItem(oldKey)
    }
  }
} catch {
  // private mode
}

// @gen-schemes:start (generated by gen-schemes.mjs, do not edit)
export const GEN_LIGHT_SCHEMES = ['nord-light', 'ayu-light', 'everforest-light', 'gruvbox-light', 'iceberg-light', 'kanagawa-lotus', 'dayfox', 'rose-pine-dawn', 'tokyo-night-day', 'light-owl', 'github-light', 'vitesse-light', 'flexoki-light', 'one-light', 'alucard'] as const
export const GEN_DARK_SCHEMES = ['catppuccin-mocha', 'catppuccin-macchiato', 'catppuccin-frappe', 'solarized-dark', 'nord', 'monokai', 'sonokai', 'ayu-dark', 'ayu-mirage', 'everforest-dark', 'gruvbox-dark', 'iceberg', 'jellybeans', 'kanagawa-wave', 'kanagawa-dragon', 'nightfox', 'rose-pine', 'rose-pine-moon', 'tokyo-night', 'tokyo-night-storm', 'night-owl', 'github-dark', 'vitesse-dark', 'flexoki-dark'] as const
export const GEN_PAGE_BG = {
  'catppuccin-mocha': 'oklch(0.243 0.03 283.9)',
  'catppuccin-macchiato': 'oklch(0.279 0.035 276.9)',
  'catppuccin-frappe': 'oklch(0.329 0.032 274.8)',
  'solarized-dark': 'oklch(0.267 0.049 219.8)',
  'nord': 'oklch(0.324 0.023 264.2)',
  'nord-light': 'oklch(0.951 0.007 260.7)',
  'monokai': 'oklch(0.274 0.011 114.8)',
  'sonokai': 'oklch(0.302 0.011 271)',
  'ayu-dark': 'oklch(0.173 0.015 266.7)',
  'ayu-mirage': 'oklch(0.261 0.024 267.1)',
  'ayu-light': 'oklch(0.982 0.002 247.8)',
  'everforest-dark': 'oklch(0.324 0.015 240.4)',
  'everforest-light': 'oklch(0.952 0.031 98.9)',
  'gruvbox-dark': 'oklch(0.277 0 0)',
  'gruvbox-light': 'oklch(0.956 0.055 96.2)',
  'iceberg': 'oklch(0.211 0.018 275)',
  'iceberg-light': 'oklch(0.934 0.004 271.4)',
  'jellybeans': 'oklch(0.196 0 0)',
  'kanagawa-wave': 'oklch(0.243 0.017 285.1)',
  'kanagawa-dragon': 'oklch(0.203 0.003 17.4)',
  'kanagawa-lotus': 'oklch(0.936 0.063 101.6)',
  'nightfox': 'oklch(0.253 0.029 255.2)',
  'dayfox': 'oklch(0.963 0.007 67.7)',
  'rose-pine': 'oklch(0.213 0.025 291.1)',
  'rose-pine-moon': 'oklch(0.26 0.039 287.7)',
  'rose-pine-dawn': 'oklch(0.97 0.011 71.9)',
  'tokyo-night': 'oklch(0.226 0.021 280.5)',
  'tokyo-night-storm': 'oklch(0.282 0.036 274.7)',
  'tokyo-night-day': 'oklch(0.913 0.007 277.2)',
  'night-owl': 'oklch(0.193 0.045 244)',
  'light-owl': 'oklch(0.988 0 0)',
  'github-dark': 'oklch(0.176 0.014 258.4)',
  'github-light': 'oklch(1 0 0)',
  'vitesse-dark': 'oklch(0.182 0 0)',
  'vitesse-light': 'oklch(1 0 0)',
  'flexoki-dark': 'oklch(0.17 0.002 17.3)',
  'flexoki-light': 'oklch(0.99 0.016 95.2)',
  'one-light': 'oklch(0.985 0 0)',
  'alucard': 'oklch(0.987 0.021 95.3)',
} as const
// @gen-schemes:end

export const LIGHT_SCHEMES = ['default', 'latte', 'solarized', ...GEN_LIGHT_SCHEMES] as const
export const DARK_SCHEMES = ['default', 'dracula', 'onedark', ...GEN_DARK_SCHEMES] as const
export type LightScheme = (typeof LIGHT_SCHEMES)[number]
export type DarkScheme = (typeof DARK_SCHEMES)[number]

/** Page background per scheme, mirroring --background in index.css and the
 * generated blocks in schemes.gen.css. */
export const PAGE_BG = {
  light: 'oklch(0.985 0.003 80)',
  dark: 'oklch(0.172 0.005 56)',
  latte: 'oklch(0.933 0.009 265)',
  solarized: 'oklch(0.952 0.026 91)',
  dracula: 'oklch(0.288 0.022 278)',
  onedark: 'oklch(0.293 0.016 264)',
  ...GEN_PAGE_BG,
} as const

const systemDark = () => window.matchMedia('(prefers-color-scheme: dark)')

/** Stored preference. Anything unrecognized counts as auto. */
export function getTheme(): Theme {
  const stored = localStorage.getItem(THEME_KEY)
  return stored === 'light' || stored === 'dark' ? stored : 'auto'
}

/** Stored scheme per side. Anything unrecognized counts as default. */
export function getLightScheme(): LightScheme {
  const stored = localStorage.getItem(SCHEME_LIGHT_KEY) as LightScheme | null
  return stored && LIGHT_SCHEMES.includes(stored) ? stored : 'default'
}

export function getDarkScheme(): DarkScheme {
  const stored = localStorage.getItem(SCHEME_DARK_KEY) as DarkScheme | null
  return stored && DARK_SCHEMES.includes(stored) ? stored : 'default'
}

/** Which of the two sides a preference resolves to right now. */
export function isDark(theme: Theme = getTheme()): boolean {
  return theme === 'dark' || (theme === 'auto' && systemDark().matches)
}

/** Page background the current preferences resolve to. */
export function pageBg(): string {
  if (isDark()) {
    const scheme = getDarkScheme()
    return scheme === 'default' ? PAGE_BG.dark : PAGE_BG[scheme]
  }
  const scheme = getLightScheme()
  return scheme === 'default' ? PAGE_BG.light : PAGE_BG[scheme]
}

const SCHEME_CLASSES = [...LIGHT_SCHEMES, ...DARK_SCHEMES]
  .filter((s) => s !== 'default')
  .map((s) => `scheme-${s}`)

function store(key: string, value: string): void {
  try {
    localStorage.setItem(key, value)
  } catch {
    // private mode: the choice lives for this page only
  }
}

// True while a scheme is being painted without being stored.
let previewing = false

/** Paint a scheme without storing it. A reload always lands on the saved state. */
export function previewScheme(rootEl: HTMLElement, side: 'light' | 'dark', scheme: string): void {
  previewing = true
  rootEl.classList.toggle('dark', side === 'dark')
  rootEl.classList.remove(...SCHEME_CLASSES)
  if (scheme !== 'default') rootEl.classList.add(`scheme-${scheme}`)
  const bg = scheme === 'default' ? PAGE_BG[side] : PAGE_BG[scheme as keyof typeof PAGE_BG]
  document.documentElement.style.setProperty('background-color', bg, 'important')
}

/** Back to the saved state; a no-op when nothing is being previewed. */
export function clearPreview(rootEl: HTMLElement): void {
  if (!previewing) return
  applyTheme(rootEl)
}

export function applyTheme(rootEl: HTMLElement, theme?: Theme) {
  previewing = false
  if (theme) store(THEME_KEY, theme)
  const dark = isDark(theme ?? getTheme())
  rootEl.classList.toggle('dark', dark)
  const scheme = dark ? getDarkScheme() : getLightScheme()
  rootEl.classList.remove(...SCHEME_CLASSES)
  if (scheme !== 'default') rootEl.classList.add(`scheme-${scheme}`)
  // The canvas behind #mam-root: overscroll and anything reaching below the host
  // shows it, so it carries the page color instead of the default white.
  document.documentElement.style.setProperty('background-color', pageBg(), 'important')
}

export function setLightScheme(rootEl: HTMLElement, scheme: LightScheme) {
  store(SCHEME_LIGHT_KEY, scheme)
  applyTheme(rootEl)
}

export function setDarkScheme(rootEl: HTMLElement, scheme: DarkScheme) {
  store(SCHEME_DARK_KEY, scheme)
  applyTheme(rootEl)
}

/** On auto, a system switch repaints straight away instead of at the next load. */
export function watchSystemTheme(rootEl: HTMLElement): void {
  systemDark().addEventListener('change', () => {
    if (getTheme() === 'auto') applyTheme(rootEl)
  })
}
