// Theme preference and the page backgrounds. Kept free of imports so the
// boot guard can use it as the very first module in the bundle.

export type Theme = 'light' | 'dark' | 'auto'

export const THEME_KEY = 'colophon:theme'
export const SCHEME_LIGHT_KEY = 'colophon:scheme-light'
export const SCHEME_DARK_KEY = 'colophon:scheme-dark'

// One-time rename from the old prefix. This module loads first and stays
// import-free, so it migrates its own keys inline before the first read.
try {
  for (const [oldKey, newKey] of [
    ['mam-remaster:theme', THEME_KEY],
    ['mam-remaster:scheme-light', SCHEME_LIGHT_KEY],
    ['mam-remaster:scheme-dark', SCHEME_DARK_KEY],
  ]) {
    const value = localStorage.getItem(oldKey)
    if (value !== null) {
      if (localStorage.getItem(newKey) === null) localStorage.setItem(newKey, value)
      localStorage.removeItem(oldKey)
    }
  }
} catch {
  // private mode
}

// @gen-schemes:start (generated by gen-schemes.mjs, do not edit)
export const GEN_LIGHT_SCHEMES = ['nord-light', 'ayu-light', 'everforest-light', 'gruvbox-light', 'iceberg-light', 'kanagawa-lotus', 'dayfox', 'rose-pine-dawn', 'tokyo-night-day', 'light-owl', 'github-light', 'vitesse-light', 'flexoki-light', 'one-light', 'alucard'] as const
export const GEN_DARK_SCHEMES = ['catppuccin-mocha', 'catppuccin-macchiato', 'catppuccin-frappe', 'solarized-dark', 'nord', 'monokai', 'sonokai', 'ayu-dark', 'ayu-mirage', 'everforest-dark', 'gruvbox-dark', 'iceberg', 'jellybeans', 'kanagawa-wave', 'kanagawa-dragon', 'nightfox', 'rose-pine', 'rose-pine-moon', 'tokyo-night', 'tokyo-night-storm', 'night-owl', 'github-dark', 'vitesse-dark', 'flexoki-dark'] as const
export const GEN_PAGE_BG = {
  'catppuccin-mocha': 'oklch(0.2429 0.0304 283.91)',
  'catppuccin-macchiato': 'oklch(0.2788 0.0353 276.94)',
  'catppuccin-frappe': 'oklch(0.3291 0.0324 274.76)',
  'solarized-dark': 'oklch(0.2673 0.0486 219.82)',
  'nord': 'oklch(0.3244 0.0229 264.18)',
  'nord-light': 'oklch(0.933 0.0104 261.79)',
  'monokai': 'oklch(0.2737 0.0109 114.8)',
  'sonokai': 'oklch(0.3016 0.0112 271.03)',
  'ayu-dark': 'oklch(0.1733 0.0154 266.68)',
  'ayu-mirage': 'oklch(0.2609 0.0238 267.11)',
  'ayu-light': 'oklch(0.9816 0.0017 247.84)',
  'everforest-dark': 'oklch(0.3239 0.0153 240.42)',
  'everforest-light': 'oklch(0.9522 0.0306 98.86)',
  'gruvbox-dark': 'oklch(0.2768 0 0)',
  'gruvbox-light': 'oklch(0.9555 0.0555 96.15)',
  'iceberg': 'oklch(0.2112 0.0181 274.98)',
  'iceberg-light': 'oklch(0.9037 0.0114 269.54)',
  'jellybeans': 'oklch(0.1957 0 0)',
  'kanagawa-wave': 'oklch(0.2433 0.017 285.06)',
  'kanagawa-dragon': 'oklch(0.2025 0.0032 17.42)',
  'kanagawa-lotus': 'oklch(0.8927 0.0596 99.07)',
  'nightfox': 'oklch(0.2529 0.0286 255.22)',
  'dayfox': 'oklch(0.8986 0.014 67.65)',
  'rose-pine': 'oklch(0.2134 0.0255 291.13)',
  'rose-pine-moon': 'oklch(0.2604 0.039 287.73)',
  'rose-pine-dawn': 'oklch(0.9699 0.0113 71.9)',
  'tokyo-night': 'oklch(0.2263 0.0214 280.49)',
  'tokyo-night-storm': 'oklch(0.2819 0.0355 274.75)',
  'tokyo-night-day': 'oklch(0.8734 0.02 270.19)',
  'night-owl': 'oklch(0.1928 0.0452 243.97)',
  'light-owl': 'oklch(0.9731 0 0)',
  'github-dark': 'oklch(0.1763 0.014 258.36)',
  'github-light': 'oklch(0.9782 0.0034 247.86)',
  'vitesse-dark': 'oklch(0.1822 0 0)',
  'vitesse-light': 'oklch(0.9761 0 0)',
  'flexoki-dark': 'oklch(0.1696 0.0017 17.32)',
  'flexoki-light': 'oklch(0.9537 0.0147 98.29)',
  'one-light': 'oklch(0.9851 0 0)',
  'alucard': 'oklch(0.9336 0.0137 92.99)',
} as const
// @gen-schemes:end

export const LIGHT_SCHEMES = ['default', 'latte', 'solarized', ...GEN_LIGHT_SCHEMES] as const
export const DARK_SCHEMES = ['default', 'dracula', 'onedark', ...GEN_DARK_SCHEMES] as const
export type LightScheme = (typeof LIGHT_SCHEMES)[number]
export type DarkScheme = (typeof DARK_SCHEMES)[number]

/** Page background per scheme, mirroring --background in index.css and the
 * generated blocks in schemes.gen.css. */
export const PAGE_BG = {
  light: 'oklch(0.985 0.003 80)',
  dark: 'oklch(0.172 0.005 56)',
  latte: 'oklch(0.933 0.009 265)',
  solarized: 'oklch(0.952 0.026 91)',
  dracula: 'oklch(0.288 0.022 278)',
  onedark: 'oklch(0.293 0.016 264)',
  ...GEN_PAGE_BG,
} as const

const systemDark = () => window.matchMedia('(prefers-color-scheme: dark)')

/** Stored preference. Anything unrecognized counts as auto. */
export function getTheme(): Theme {
  const stored = localStorage.getItem(THEME_KEY)
  return stored === 'light' || stored === 'dark' ? stored : 'auto'
}

/** Stored scheme per side. Anything unrecognized counts as default. */
export function getLightScheme(): LightScheme {
  const stored = localStorage.getItem(SCHEME_LIGHT_KEY) as LightScheme | null
  return stored && LIGHT_SCHEMES.includes(stored) ? stored : 'default'
}

export function getDarkScheme(): DarkScheme {
  const stored = localStorage.getItem(SCHEME_DARK_KEY) as DarkScheme | null
  return stored && DARK_SCHEMES.includes(stored) ? stored : 'default'
}

/** Which of the two sides a preference resolves to right now. */
export function isDark(theme: Theme = getTheme()): boolean {
  return theme === 'dark' || (theme === 'auto' && systemDark().matches)
}

/** Page background the current preferences resolve to. */
export function pageBg(): string {
  if (isDark()) {
    const scheme = getDarkScheme()
    return scheme === 'default' ? PAGE_BG.dark : PAGE_BG[scheme]
  }
  const scheme = getLightScheme()
  return scheme === 'default' ? PAGE_BG.light : PAGE_BG[scheme]
}

const SCHEME_CLASSES = [...LIGHT_SCHEMES, ...DARK_SCHEMES]
  .filter((s) => s !== 'default')
  .map((s) => `scheme-${s}`)

function store(key: string, value: string): void {
  try {
    localStorage.setItem(key, value)
  } catch {
    // private mode: the choice lives for this page only
  }
}

// True while a scheme is being painted without being stored.
let previewing = false

/** Paint a scheme without storing it. A reload always lands on the saved state. */
export function previewScheme(rootEl: HTMLElement, side: 'light' | 'dark', scheme: string): void {
  previewing = true
  rootEl.classList.toggle('dark', side === 'dark')
  rootEl.classList.remove(...SCHEME_CLASSES)
  if (scheme !== 'default') rootEl.classList.add(`scheme-${scheme}`)
  const bg = scheme === 'default' ? PAGE_BG[side] : PAGE_BG[scheme as keyof typeof PAGE_BG]
  document.documentElement.style.setProperty('background-color', bg, 'important')
}

/** Back to the saved state; a no-op when nothing is being previewed. */
export function clearPreview(rootEl: HTMLElement): void {
  if (!previewing) return
  applyTheme(rootEl)
}

export function applyTheme(rootEl: HTMLElement, theme?: Theme) {
  previewing = false
  if (theme) store(THEME_KEY, theme)
  const dark = isDark(theme ?? getTheme())
  rootEl.classList.toggle('dark', dark)
  const scheme = dark ? getDarkScheme() : getLightScheme()
  rootEl.classList.remove(...SCHEME_CLASSES)
  if (scheme !== 'default') rootEl.classList.add(`scheme-${scheme}`)
  // The canvas behind #mam-root: overscroll and anything reaching below the host
  // shows it, so it carries the page color instead of the default white.
  document.documentElement.style.setProperty('background-color', pageBg(), 'important')
}

export function setLightScheme(rootEl: HTMLElement, scheme: LightScheme) {
  store(SCHEME_LIGHT_KEY, scheme)
  applyTheme(rootEl)
}

export function setDarkScheme(rootEl: HTMLElement, scheme: DarkScheme) {
  store(SCHEME_DARK_KEY, scheme)
  applyTheme(rootEl)
}

/** On auto, a system switch repaints straight away instead of at the next load. */
export function watchSystemTheme(rootEl: HTMLElement): void {
  systemDark().addEventListener('change', () => {
    if (getTheme() === 'auto') applyTheme(rootEl)
  })
}
